[phases.setup]
aptPkgs = ["postgresql-client"]

[phases.install]
cmds = [
  "pip install -r requirements.txt", 
  "cd src/frontend && npm ci --production --no-optional && npm run build"
]

[start]
cmd = "./docker_entrypoint.sh"
