[build]
builder = "NIXPACKS"

[deploy]
startCommand = "sh -c \"python -m uvicorn src.api.main:app --host 0.0.0.0 --port ${PORT:-5432}\""
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
